version: "3.9"
services:
  psql_database:
    image: postgres:14-alpine
    container_name: psql_database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
volumes:
  data:
    driver: local