version: "3.9"
services:
  db:
    image: postgres:14-alpine
    container_name: ${DB_NAME}
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
  cxp_api:
    container_name: cxp_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  data:
    driver: local
